version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1cmqjlpxryxqt"
s3_prefix = "sam-app"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "pAthenaWorkgroupName=\"primary\" pGlueDatabaseName=\"covid-19\" pBucketName=\"takehome-raw-layer\" TableName=\"websocket_connections\""

